name: wasteagram
description: CS 492 Project 5

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  location: ^3.0.0
  image_picker: ^0.6.7
  share: ^0.6.4
  http: ^0.12.2
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6
  cupertino_icons: ^0.1.3
  flutter_datetime_formfield: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
